const supportAttributes = [
  "ticketNumber",
  "role",
  "reporterID",
  "priority",
  "fullName",
  "email",
  "mobile",
  "subject",
  "description",
  "supportingDocuments",
  "raisedOn",
  "resolvedOn",
  "assignedTo",
  "remarks",
  "status",
  "escalatedTo",
  "escalationRemark",
  "chat",
];

const searchSupportAttributes = [
  "ticketNumber",
  "role",
  "reporterID",
  "priority",
  "fullName",
  "email",
  "mobile",
  "subject",
  "description",
  "supportingDocuments",
  "raisedOn",
  "resolvedOn",
  "assignedTo",
  "remarks",
  "status",
  "escalatedTo",
  "escalationRemark",
  "chat",
  "numberOfDocumentsToPick",
  "filter",
  "sortBy",
];

const updateSupportAttributes = [
  "id",
  "priority",
  "role",
  "supportingDocuments",
  "resolvedOn",
  "assignedTo",
  "remarks",
  "status",
  "escalatedTo",
  "escalationRemark",
  "chat",
];

const createNewSupportAttributes = [
  "role",
  "reporterID",
  "priority",
  "fullName",
  "email",
  "mobile",
  "subject",
  "description",
  "supportingDocuments",
  "raisedOn",
  "status",
];
const supportStatus = [
  "waitingForSupport",
  "inProgress",
  "resolved",
  "cancelled",
  "escalated",
  "closed",
  "waitingForCustomer",
];

module.exports = {
  supportAttributes,
  createNewSupportAttributes,
  updateSupportAttributes,
  searchSupportAttributes,
};
