const bookingAttributes = [
  "doctorId",
  "clinicDetails",
  "clinicId",
  "sessionId",
  "slotId",
  "reasonForVisit",
  "appointmentType",
  "slotTime",
  "slotDay",
  "userId",
  "bookingTimeStamp",
  "appointmentDate",
  "sessionStartTime",
  "sessionEndTime",
  "slotType",
  "userType",
  "predictedSlotTime",
  "endTime",
  "pin",
  "dob",
  "gender",
  "userName",
  "paymentStatus",
];

const bookingUpdateAttributes = [
  "doctorId",
  "status",
  "id",
  "role",
  "clinicDetails",
  "sessionId",
  "slotId",
  "userId",
  "reasonForVisit",
  "appointmentType",
  "slotTime",
  "symptoms",
  "tests",
  "diagnosis",
  "slotDay",
  "bookingTimeStamp",
  "appointmentDate",
  "sessionStartTime",
  "sessionEndTime",
  "nextApptDate",
  "slotType",
  "clinicId",
  "medicine",
  "predictedSlotTime",
  "actualEndTime",
  "endTime",
  "pin",
  "dob",
  "gender",
  "userName",
  "paymentStatus",
];

const searchInBooking = ["filters", "sort", "search", "pageNo", "pageSize"];
const cancelDoctorSession = ["doctorId", "sessionId", "status"];

const searchAttributes = [
  "doctorId",
  "status",
  "userId",
  "appointmentId",
  "clinicDetails",
  "sessionId",
  "slotId",
  "reasonForVisit",
  "appointmentType",
  "slotTime",
  "slotDay",
  "bookingTimeStamp",
  "appointmentDate",
  "sessionStartTime",
  "sessionEndTime",
  "slotType",
  "userType",
  "clinicId",
  "range",
  "predictedSlotTime",
  "actualEndTime",
  "endTime",
  "pin",
  "dob",
  "gender",
  "userName",
  "paymentStatus",
];

const filterAttributes = [
  "doctorId",
  "status",
  "userId",
  "sessionId",
  "appointmentType",
  "slotDay",
  "appointmentDate",
  "slotType",
  "clinicDetails",
  "userType",
  "clinicId",
  "pin",
  "dob",
  "gender",
  "userName",
  "paymentStatus",
];

const unRegBookingAttributes = [
  "doctorId",
  "clinicDetails",
  "clinicId",
  "sessionId",
  "reasonForVisit",
  "appointmentType",
  "diagnosis",
  "slotDay",
  "bookingTimeStamp",
  "appointmentDate",
  "sessionStartTime",
  "sessionEndTime",
  "slotType",
  "userType",
  "duration",
  "mobile",
  "userName",
  "predictedSlotTime",
  "endTime",
  "pin",
  "dob",
  "gender",
  "paymentStatus",
];

const sortAttributes = [
  "slotTime",
  "bookingTimeStamp",
  "slotId",
  "sessionStartTime",
  "sessionEndTime",
  "appointmentDate",
  "predictedSlotTime",
  "actualEndTime",
  "endTime",
  "dob",
  "gender",
  "paymentStatus",
];
const sessionDelayAttributes = [
  "doctorId",
  "sessionDelayDuration",
  "sessionId",
  "sessionDate",
  "message",
];
const weekday = [
  "Sunday",
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
];
const queueAttributes = ["sessionId"];

module.exports = {
  bookingAttributes,
  bookingUpdateAttributes,
  searchInBooking,
  sortAttributes,
  filterAttributes,
  searchAttributes,
  unRegBookingAttributes,
  sessionDelayAttributes,
  weekday,
  queueAttributes,
  cancelDoctorSession,
};
