const userReviewsAttributes = [
  "role",
  "reviewRating",
  "reviewMessage",
  "reviewDate",
  "userId",
  "userName",
  "isVerifiedUser",
  "doctorId",
  "reviewlastEditedOn",
  "medical_details",
  "userScheduleId",
  // "accurateDiagnosisRating",
  // "friendlinessAndWaitTimeRating",
  // "bedsideMannerismRating",
  // "staffCourteousnessRating",
  // "patientEducationRating",
  "reviewTags",
];

const userReviewsCreationAttributes = [
  "role",
  "reviewRating",
  "reviewMessage",
  "reviewDate",
  "userId",
  "userName",
  "isVerifiedUser",
  "doctorId",
  "medical_details",
  "userScheduleId",
  "reviewTags",
];

const doctorUpdateAttributes = [
  "address",
  "ailmentsTreated",
  "averageRating",
  "city",
  "country",
  "designation",
  "education",
  "email",
  "experience",
  "firstName",
  "gender",
  "hospital",
  "testsKeywordList",
  "symptomsKeywordList",
  "identifier",
  "isPersonAllowed",
  "isVideoAllowed",
  "landmark",
  "languages",
  "lastName",
  "licenses",
  "locality",
  "practiceStaff",
  "location",
  "name",
  "mobile",
  "schedule",
  "specialization",
  "state",
  "yearsOfExperience",
  "id",
  "role",
  "docImageUrl",
  "tags",
  "noOfReviews",
  "consultations",
  "diagnosisKeywordList",
  "testsKeywordlist",
  "symptomsKeywordList",
  "satisfiedPatients",
  "district",
  "password",
  "pin",
  "awardsAndPublications",
  "associatedClinics",
];

const reviewTags = [
  "On Time",
  "well-mannered",
  "Explains lucidly",
  "Great Staff",
  "Accurate Diagnosis",
  "Clean and Hygenic",
];
const getRequestAttributes = ["role", "doctorId", "fields"];

const sortListForReview = ["reviewRating", "reviewDate", "reviewlastEditedOn"];

const getRequestReviewAttributes = [
  "role",
  "doctorId",
  "pageSize",
  "pageNo",
  "userId",
  "sort",
];

const createNewStaffAttributes = [
  "mappedTo",
  "email",
  "designation",
  "mobile",
  "lastName",
  "firstName",
  "role",
  "profileCreationDate",
];
const getRecommendedDoctors = [
  "userId",
  "size",
  "isRandom",
  "isLatestProfiles",
  "isRegional",
  "isSpecialisation",
];
const staffUpdateAttributes = [
  "id",
  "staffId",
  "role",
  "designation",
  "password",
  "pin",
  "experience",
  "education",
  "mappedTo",
  "email",
  "mobile",
  "lastName",
  "firstName",
];

module.exports = {
  userReviewsAttributes,
  doctorUpdateAttributes,
  getRequestAttributes,
  sortListForReview,
  getRequestReviewAttributes,
  createNewStaffAttributes,
  staffUpdateAttributes,
  userReviewsCreationAttributes,
  reviewTags,
  getRecommendedDoctors,
};
